import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { PokemonPage } from "../types";
import Header from "../header";
import Footer from "../footer";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { useRouter } from "next/router";
import PaginationPage from "../components/paginationPage";
import InfiniteScrollPage from "../components/infinitScrollPage";
import { useDebouncedCallback } from "use-debounce";

export const imageLoader = (id: string | string[] | undefined) => {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
};
export const fetcherGraphQL = (offset = 0, limit = 16, search = "") =>
  fetch("https://beta.pokeapi.co/graphql/v1beta", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      query: `query getPokemons($offset: Int = 0, $limit: Int = 16, $_like: String = "%${search}%") {
        pokemon_v2_pokemon(offset: $offset, limit: $limit, where: {name: {_ilike:$_like }}) {
          id
          name
        }
        pokemon_v2_pokemon_aggregate(where: {name: {_ilike: $_like}}) {
          aggregate {
            count
          }
        }
      }
      `,
      variables: {
        offset: offset,
        limit: limit,
      },
    }),
  }).then((res) => res.json());
export const getServerSideProps: GetServerSideProps<{
  pokemonPage: PokemonPage;
}> = async () => {
  try {
    const pokemonPage: PokemonPage = await fetcherGraphQL();
    return {
      props: {
        pokemonPage,
      },
    };
  } catch {
    return {
      notFound: true,
    };
  }
};

export default function Home({
  pokemonPage,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const { push, query } = useRouter();
  const [pageView, setPageView] = useState<string>("pages");
  const [search, setSearch] = useState((query.search as string) || "");
  const [pagination, setPagination] = useState({
    limit: Number(query.limit) || 16,
    offset: Number(query.offset) || 0,
  });

  const defferedSearch = useDebouncedCallback((search: string) => {
    setSearch(search);
  }, 500);

  useEffect(() => {
    const params = new URLSearchParams(document.location.search);
    const view = params.get("view");
    if (view) {
      setPageView(view);
    }
    setSearch((query.search as string) || "");
  }, []);
  useEffect(() => {
    if (!search.length) {
      delete query.search;
    }
    push({ query: { ...query, view: pageView } }, undefined, {
      shallow: true,
    });
  }, [pageView, search]);

  const handleClickViewAll = () => {
    setPageView("all");
    setPagination(
      { limit: Number(query.limit) || 16, offset: Number(query.offset) } || 0
    );
    delete query.limit;
    delete query.offset;
  };
  const handleCLickViewPage = () => {
    setPageView("pages");
  };
  const handleSearchField = (event: Event) => {
    if (event.target instanceof HTMLInputElement) {
      push({ query: { ...query, search: event.target.value } }, undefined, {
        shallow: true,
      });
      defferedSearch(event.target.value);
      // setSearch(event.target.value);
    }
  };

  return (
    <>
      <Head>
        <title>POKEMON API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        searchField={search}
        pokemonsCounter={
          pokemonPage.data.pokemon_v2_pokemon_aggregate.aggregate.count
        }
        btnNameAllView={"ALL"}
        btnNamePageView={"PAGE"}
        handleClickAllView={handleClickViewAll}
        handleClickPageView={handleCLickViewPage}
        handleSearch={(event: Event) => handleSearchField(event)}
      />
      <main className={styles.main}>
        {pageView === "pages" ? (
          <PaginationPage
            pokemonPage={pokemonPage}
            search={search}
            page={pagination}
          />
        ) : (
          <InfiniteScrollPage pokemonPage={pokemonPage} search={search} />
        )}
      </main>
      <Footer />
    </>
  );
}
