import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useDeferredValue, useEffect, useState } from "react";
import { PokemonPage } from "../types";
import Header from "../header";
import Footer from "../footer";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { useRouter } from "next/router";
import PaginationPage from "../components/paginationPage";
import InfiniteScrollPage from "../components/infinitScrollPage";
import { useDebounce, useDebouncedCallback } from "use-debounce";

export const imageLoader = (id: string | string[] | undefined) => {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
};
export const getServerSideProps: GetServerSideProps<{
  pokemonPage: PokemonPage;
}> = async () => {
  try {
    const params = new URLSearchParams();
    const limit = params.get("limit");
    const offset = params.get("offset");
    const res = await fetch(
      `https://pokeapi.co/api/v2/pokemon/?limit=${limit || 16}&offset=${
        offset || 0
      }`
    );
    const pokemonPage: PokemonPage = await res.json();
    return {
      props: {
        pokemonPage,
      },
    };
  } catch {
    return {
      notFound: true,
    };
  }
};

export const fetcher = (link: string) => fetch(link).then((res) => res.json());

export default function Home({
  pokemonPage,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const { push, query } = useRouter();
  const [pageView, setPageView] = useState<string>("pages");
  const [search, setSearch] = useState((query.search as string) || "");
  // const [defferedSearch] = useDebounce(search, 350);
  const defferedSearch = useDebouncedCallback(
    (search: string) => setSearch(search),
    350
  );
  // const defferedSearch = useDeferredValue(search);
  const [pagination, setPagination] = useState({
    limit: Number(query.limit) || 16,
    offset: Number(query.offset) || 0,
  });

  useEffect(() => {
    const params = new URLSearchParams(document.location.search);
    const view = params.get("view");
    if (view) {
      setPageView(view);
    }
    setSearch((query.search as string) || "");
  }, []);
  useEffect(() => {
    if (!search.length) {
      delete query.search;
    }
    push({ query: { ...query, view: pageView } }, undefined, {
      shallow: true,
    });
  }, [pageView]);

  const handleClickViewAll = () => {
    setPageView("all");
    setPagination(
      { limit: Number(query.limit) || 16, offset: Number(query.offset) } || 0
    );
    delete query.limit;
    delete query.offset;
  };
  const handleCLickViewPage = () => {
    setPageView("pages");
  };
  const handleSearchField = (event: Event) => {
    if (event.target instanceof HTMLInputElement) {
      push({ query: { ...query, search: event.target.value } }, undefined, {
        shallow: true,
      });
      defferedSearch(event.target.value);
      // setSearch(event.target.value);
    }
  };

  return (
    <>
      <Head>
        <title>POKEMON API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        searchField={search}
        pokemonsCounter={pokemonPage.count}
        btnNameAllView={"ALL"}
        btnNamePageView={"PAGE"}
        handleClickAllView={handleClickViewAll}
        handleClickPageView={handleCLickViewPage}
        handleSearch={(event: Event) => handleSearchField(event)}
      />
      <main className={styles.main}>
        {pageView === "pages" ? (
          <PaginationPage
            pokemonPage={pokemonPage}
            search={search}
            page={pagination}
          />
        ) : (
          <InfiniteScrollPage pokemonPage={pokemonPage} search={search} />
        )}
      </main>
      <Footer />
    </>
  );
}
