import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import { PokemonPage } from "../types";
import Header from "../header";
import Footer from "../footer";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import { useRouter } from "next/router";
import PaginationPage from "../components/paginationPage";
import InfiniteScrollPage from "../components/infinitScrollPage";
import { useDebouncedCallback } from "use-debounce";

export const imageLoader = (id: string | string[] | undefined) => {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
};
export const getServerSideProps: GetServerSideProps<{
  pokemonPage: PokemonPage;
}> = async () => {
  try {
    const params = new URLSearchParams();
    const limit = params.get("limit");
    const offset = params.get("offset");
    // const search = params.get("search");
    const res = await fetch(
      `https://pokeapi.co/api/v2/pokemon/?limit=${limit || 16}&offset=${
        offset || 0
      }`
    );
    const pokemonPage: PokemonPage = await res.json();
    // const res = await fetch("https://beta.pokeapi.co/graphql/v1beta", {
    //   method: "POST",
    //   headers: { "Content-Type": "application/json" },
    //   body: JSON.stringify({
    //     query: `query getSeacrhResults($limit: Int,$offset: Int){
    //       pokemon_v2_pokemon(
    //         where:{ name: { _like: "%${search}%" } }
    //         limit:$limit
    //         offset:$offset
    //       ){
    //         name
    //         id
    //       }
    //     }`,
    //     variables: {
    //       limit: limit,
    //       offset: offset,
    //     },
    //   }),
    // });
    // const pokemonPage = await res.json();
    return {
      props: {
        pokemonPage,
      },
    };
  } catch {
    return {
      notFound: true,
    };
  }
};

export const fetcher = (link: string) => fetch(link).then((res) => res.json());

export default function Home({
  pokemonPage,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const { push, query } = useRouter();
  const [pageView, setPageView] = useState<string>("pages");
  const [search, setSearch] = useState((query.search as string) || "");
  const [pagination, setPagination] = useState({
    limit: Number(query.limit) || 16,
    offset: Number(query.offset) || 0,
  });
  console.log("POKEMON PAGE", pokemonPage);

  const defferedSearch = useDebouncedCallback((search: string) => {
    setSearch(search);
    fetch("https://beta.pokeapi.co/graphql/v1beta", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        query: `query getSeacrhResults($limit: Int,$offset: Int){
          pokemon_v2_pokemon(
            where:{ name: { _like: "%${search}%" } }
            limit:$limit
            offset:$offset
          ){
            name
            id
          }
        }`,
        variables: {
          limit: pagination.limit,
          offset: pagination.offset,
        },
      }),
    })
      .then((res) => res.json())
      .then((data) => console.log("data", data));
    console.log("PAGINATION", pagination.offset, pagination.limit);
  }, 350);
  useEffect(() => {
    const params = new URLSearchParams(document.location.search);
    const view = params.get("view");
    if (view) {
      setPageView(view);
    }
    setSearch((query.search as string) || "");
  }, []);
  useEffect(() => {
    if (!search.length) {
      delete query.search;
    }
    push({ query: { ...query, view: pageView } }, undefined, {
      shallow: true,
    });
  }, [pageView, search]);

  const handleClickViewAll = () => {
    setPageView("all");
    setPagination(
      { limit: Number(query.limit) || 16, offset: Number(query.offset) } || 0
    );
    delete query.limit;
    delete query.offset;
  };
  const handleCLickViewPage = () => {
    setPageView("pages");
  };
  const handleSearchField = (event: Event) => {
    if (event.target instanceof HTMLInputElement) {
      push({ query: { ...query, search: event.target.value } }, undefined, {
        shallow: true,
      });
      defferedSearch(event.target.value);
      // setSearch(event.target.value);
    }
  };

  return (
    <>
      <Head>
        <title>POKEMON API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        searchField={search}
        pokemonsCounter={pokemonPage.count}
        btnNameAllView={"ALL"}
        btnNamePageView={"PAGE"}
        handleClickAllView={handleClickViewAll}
        handleClickPageView={handleCLickViewPage}
        handleSearch={(event: Event) => handleSearchField(event)}
      />
      <div id="fetcher"></div>
      <main className={styles.main}>
        {pageView === "pages" ? (
          <PaginationPage
            pokemonPage={pokemonPage}
            search={search}
            page={pagination}
          />
        ) : (
          <InfiniteScrollPage pokemonPage={pokemonPage} search={search} />
        )}
      </main>
      <Footer />
    </>
  );
}

// fetch("https://beta.pokeapi.co/graphql/v1beta", {
//   method: "POST",
//   headers: { "Content-Type": "application/json" },
//   body: JSON.stringify({
//     query: `query getSeacrhResults($limit: Int = 16,$offset: Int = 0,$search: String = ""){
//       pokemon_v2_pokemonspecies(
//         where:{ name: { _like: "$search" } }
//         limit:$limit
//         offset:$offset
//       ){
//         name
//         id
//       }
//     }`,
//     variables: {
//       limit: 16,
//       offset: 0,
//       search: "%chi%",
//     },
//   }),
// })
//   .then((res) => res.json())
//   .then((data) => console.log("DATA", data));
