import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState, useDeferredValue } from "react";
import { PokemonsAPI } from "./types";
import Footer from "./footer";
import Header from "./header";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
export const myLoader = (id: string | string[] | undefined) => {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;
};

export default function Home() {
  const [pokemons, setPokemons] = useState<PokemonsAPI>();
  const [count, setCount] = useState(1);
  const allPokemons = Math.floor(pokemons?.count ? pokemons.count / 16 : 1);
  const fetcher = (link: string) => {
    fetch(link)
      .then((res) => res.json())
      .then((data: PokemonsAPI) => {
        setPokemons(data);
      })
      .catch((e) => console.log(e));
  };
  useEffect(
    () => fetcher("https://pokeapi.co/api/v2/pokemon/?limit=16&offset=0"),
    []
  );
  return (
    <>
      <Head>
        <title>POKEMON API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header pokemonsCounter={pokemons?.count ? pokemons.count : 0} />
      <main className={styles.main}>
        <div className={styles["main-table"]}>
          {pokemons?.results.map((item) => {
            const urlSplit = item.url.split("/");
            const id = urlSplit[urlSplit.length - 2];
            return (
              <Link
                key={id}
                id={id}
                className={styles["main-item"]}
                href={`pokemon/${id}`}
              >
                <Image
                  unoptimized
                  loader={() => myLoader(id)}
                  src={myLoader(id)}
                  alt={item.name}
                  width={150}
                  height={150}
                />
                {item.name}
              </Link>
            );
          })}
        </div>
        <div className={styles["main-btns"]}>
          <button
            className={styles["main-btn"]}
            onClick={() => {
              if (pokemons?.previous) {
                fetcher(pokemons?.previous);
                setCount(count - 1);
              }
            }}
          >
            Previos Page
          </button>
          <div className={styles.pagination}>
            <input
              className={styles["pagination-input"]}
              type="number"
              name="page"
              id="page"
              min={1}
              value={count}
              onChange={(event) => {
                if (event.target instanceof HTMLInputElement) {
                  if (+event.target.value > allPokemons) {
                    event.target.value = `${allPokemons}`;
                  } else if (+event.target.value < 1) {
                    event.target.value = "1";
                  }
                  const value =
                    event.target.value === "1" ? 0 : 16 * +event.target.value;
                  fetcher(
                    `https://pokeapi.co/api/v2/pokemon/?limit=16&offset=${value}`
                  );
                  setCount(+event.target.value);
                }
              }}
            />
            <div>/ {allPokemons}</div>
          </div>
          <button
            className={styles["main-btn"]}
            onClick={() => {
              if (pokemons?.next) {
                fetcher(pokemons?.next);
                setCount(count + 1);
              }
            }}
          >
            Next Page
          </button>
        </div>
      </main>
      <Footer />
    </>
  );
}
